export type ReadinessStatus = 'Done' | 'Needs setup' | 'Blocked' | 'Ready' | 'Connected' | 'Failed' | 'Queued';
export type ReadinessRow = { id: string; area: string; name: string; owner: string; status: ReadinessStatus; evidence: string; nextAction: string };
export type ProductionReadinessSnapshot = { connectors: ReadinessRow[]; authControls: ReadinessRow[]; auditExports: ReadinessRow[]; notificationOutbox: ReadinessRow[]; deploymentChecklist: ReadinessRow[] };
function rows(prefix: string, area: string, owner: string, names: string[]): ReadinessRow[] { return names.map((name, index) => ({ id: prefix + '-' + (index + 1), area, name, owner: index % 4 === 0 ? owner : index % 3 === 0 ? 'Platform Lead' : 'Operations Lead', status: index % 7 === 0 ? 'Blocked' : index % 5 === 0 ? 'Needs setup' : index % 3 === 0 ? 'Queued' : 'Done', evidence: name + ' evidence packet ' + (index + 1), nextAction: index % 7 === 0 ? 'Add production credentials or owner approval' : index % 5 === 0 ? 'Complete setup and rerun readiness check' : 'Monitor and keep evidence current' })); }
export const productionReadinessSnapshot: ProductionReadinessSnapshot = {
  connectors: rows('connector', 'Connectors', "Agent QA", ["Enterprise Agent Testing Sandbox source connector 1","Enterprise Agent Testing Sandbox source connector 2","Enterprise Agent Testing Sandbox source connector 3","Enterprise Agent Testing Sandbox source connector 4","Enterprise Agent Testing Sandbox source connector 5","Enterprise Agent Testing Sandbox source connector 6","Enterprise Agent Testing Sandbox source connector 7","Enterprise Agent Testing Sandbox source connector 8","Enterprise Agent Testing Sandbox source connector 9","Enterprise Agent Testing Sandbox source connector 10","Enterprise Agent Testing Sandbox source connector 11","Enterprise Agent Testing Sandbox source connector 12","Enterprise Agent Testing Sandbox source connector 13","Enterprise Agent Testing Sandbox source connector 14","Enterprise Agent Testing Sandbox source connector 15"]),
  authControls: rows('auth', 'Enterprise Auth', 'Security Lead', ["SSO/MFA role mapping control 1","SSO/MFA role mapping control 2","SSO/MFA role mapping control 3","SSO/MFA role mapping control 4","SSO/MFA role mapping control 5","SSO/MFA role mapping control 6","SSO/MFA role mapping control 7","SSO/MFA role mapping control 8","SSO/MFA role mapping control 9","SSO/MFA role mapping control 10","SSO/MFA role mapping control 11","SSO/MFA role mapping control 12","SSO/MFA role mapping control 13","SSO/MFA role mapping control 14","SSO/MFA role mapping control 15"]),
  auditExports: rows('audit', 'Audit Exports', 'Compliance Lead', ["Enterprise Agent Testing Sandbox audit export packet 1","Enterprise Agent Testing Sandbox audit export packet 2","Enterprise Agent Testing Sandbox audit export packet 3","Enterprise Agent Testing Sandbox audit export packet 4","Enterprise Agent Testing Sandbox audit export packet 5","Enterprise Agent Testing Sandbox audit export packet 6","Enterprise Agent Testing Sandbox audit export packet 7","Enterprise Agent Testing Sandbox audit export packet 8","Enterprise Agent Testing Sandbox audit export packet 9","Enterprise Agent Testing Sandbox audit export packet 10","Enterprise Agent Testing Sandbox audit export packet 11","Enterprise Agent Testing Sandbox audit export packet 12","Enterprise Agent Testing Sandbox audit export packet 13","Enterprise Agent Testing Sandbox audit export packet 14","Enterprise Agent Testing Sandbox audit export packet 15"]),
  notificationOutbox: rows('notice', 'Notification Delivery', 'Operations Lead', ["Enterprise Agent Testing Sandbox notification delivery test 1","Enterprise Agent Testing Sandbox notification delivery test 2","Enterprise Agent Testing Sandbox notification delivery test 3","Enterprise Agent Testing Sandbox notification delivery test 4","Enterprise Agent Testing Sandbox notification delivery test 5","Enterprise Agent Testing Sandbox notification delivery test 6","Enterprise Agent Testing Sandbox notification delivery test 7","Enterprise Agent Testing Sandbox notification delivery test 8","Enterprise Agent Testing Sandbox notification delivery test 9","Enterprise Agent Testing Sandbox notification delivery test 10","Enterprise Agent Testing Sandbox notification delivery test 11","Enterprise Agent Testing Sandbox notification delivery test 12","Enterprise Agent Testing Sandbox notification delivery test 13","Enterprise Agent Testing Sandbox notification delivery test 14","Enterprise Agent Testing Sandbox notification delivery test 15"]),
  deploymentChecklist: rows('deploy', 'Deployment Checklist', 'Release Lead', ["Enterprise Agent Testing Sandbox production launch control 1","Enterprise Agent Testing Sandbox production launch control 2","Enterprise Agent Testing Sandbox production launch control 3","Enterprise Agent Testing Sandbox production launch control 4","Enterprise Agent Testing Sandbox production launch control 5","Enterprise Agent Testing Sandbox production launch control 6","Enterprise Agent Testing Sandbox production launch control 7","Enterprise Agent Testing Sandbox production launch control 8","Enterprise Agent Testing Sandbox production launch control 9","Enterprise Agent Testing Sandbox production launch control 10","Enterprise Agent Testing Sandbox production launch control 11","Enterprise Agent Testing Sandbox production launch control 12","Enterprise Agent Testing Sandbox production launch control 13","Enterprise Agent Testing Sandbox production launch control 14","Enterprise Agent Testing Sandbox production launch control 15"]),
};
